name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Build
        run: cargo check

      - name: Check the format
        run: cargo fmt --all -- --check

      - name: Run tests (release)
        run: cargo test --release

      - name: Run tests (debug)
        run: cargo test
